# Generated by Django 4.0.4 on 2022-11-17 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('register', models.CharField(max_length=8)),
                ('area', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Funcionario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=30)),
                ('registro', models.CharField(max_length=7)),
                ('posto', models.CharField(max_length=3)),
            ],
        ),
        migrations.CreateModel(
            name='Migrar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('migra', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Turno',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atual', models.CharField(max_length=10)),
                ('primeiraopcao', models.CharField(max_length=10)),
                ('segundaopcao', models.CharField(max_length=10)),
                ('funcionario', models.ManyToManyField(blank=True, to='sgi.funcionario')),
            ],
        ),
        migrations.CreateModel(
            name='Armario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('patrimonio', models.CharField(max_length=6)),
                ('posicao', models.CharField(max_length=10)),
                ('localizacao', models.CharField(max_length=10)),
                ('funcionario', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='Funcionario', to='sgi.funcionario')),
            ],
        ),
    ]
