# Generated by Django 4.0.4 on 2022-11-17 12:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sgi', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Migrar',
        ),
    ]
